SET SCHEMA SYSTOOLS;

CALL SYSPROC.DB2LK_GENERATE_DDL('-e -t myschema.mytable', ?);

GRANT EXECUTE ON PROCEDURE SYSPROC.DB2LK_GENERATE_DDL TO USER test;
GRANT EXECUTE ON PROCEDURE SYSPROC.DB2LK_CLEAN_TABLE TO USER test;

GRANT ALL ON SYSTOOLS.DB2LOOK_INFO TO USER test;

GRANT USAGE ON WORKLOAD SYSDEFAULTUSERWORKLOAD TO USER test;
GRANT USAGE ON SEQUENCE SYSTOOLS.DB2LOOK_TOKEN TO USER test;